### ISSUE TITLE
Error: `Undefined index: HTTP_PORT in .../example/connect.php on line 34`

### ISSUE THREAD

**Issue by SiWhite** [sleemanj/gogoTradeMe#5]
Hi there, I'm getting the following error when accessing example/connect.php on my server: 

`Undefined index: HTTP_PORT in .../example/connect.php on line 34`

The line in question is:

`if($_SERVER['HTTP_PORT'] != 443)`

I have checked my key and secret are correct in config.php, and I am using https in the browser. I am a PHP noob, so apologies if I am missing something obvious here, or if there is a better place to ask these questions. Thanks in advance!

**Comment by sleemanj** [comment]
That would be a server issue, or rather your web server is not populating the HTTP_PORT variable.

Just set it manually.

**Comment by SiWhite** [comment]
Thanks!
