### ISSUE TITLE
"Dump/Execute Any Get" issue

### ISSUE THREAD

**Issue by mpp195** [sleemanj/gogoTradeMe#8]
Hi
The "Dump Any Get" option on your example menu is giving the attached error: "The server encountered an error processing the request." (see screenshot). I'm on a Mac running osx 11.0.1, XAMPP v8.0.19. Any ideas?
Thank you for providing the framework!
Martin

![Screen Shot 2022-08-23 at 10 28 03 AM](https://user-images.githubusercontent.com/111815177/186033957-603bb8e7-e731-4300-871b-28a67d96ed2e.png)

**Comment by sleemanj** [comment]
It may be just a temporary failure on Trade Me's part - Trade Me's API server(s) are prone to falling over in various ways since they last got bought out.

Try it again a few times over the next few hours, and if it doesn't start working please bump this ticket and I'll take a look then.

**Comment by mpp195** [comment]
Thanks for the quick response.
Interestingly the option works fine if I change it to show my Watchlist instead of a General Search (see attached). Still not working with General Search though. Maybe a problem with the Sandbox as you say
![Screen Shot 2022-08-23 at 3 12 45 PM](https://user-images.githubusercontent.com/111815177/186061458-986f92aa-7558-43d1-9273-dae4fc38280e.png)
?

**Comment by sleemanj** [comment]
> Maybe a problem with the Sandbox

That would be my guess, I checked and it works in the live API.

The sandbox is pretty derelict :-(

**Comment by mpp195** [comment]
Thanks for checking - that's good news
